{% set name = "libqdldl" %}
{% set version = "0.1.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/osqp/qdldl/archive/v{{ version }}.tar.gz
    sha256: aeb1b2d76849c13e9803760a4c2e26194bf80dcc9614ae25ca6bcc404dc70d65
    patches:
      - fix_build_shared_libs_and_windows_shared.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make                               # [not win]
    - cmake

test:
  commands:
    - test -f ${PREFIX}/include/qdldl/qdldl.h  # [not win]
    - test -f ${PREFIX}/lib/libqdldl.so  # [linux]
    - test -f ${PREFIX}/lib/libqdldl.dylib  # [osx]
    - test -f ${PREFIX}/lib/cmake/qdldl/qdldl-config.cmake  # [not win]
    - if not exist %PREFIX%\\Library\\include\\qdldl\\qdldl.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\qdldl.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\qdldl.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\cmake\\qdldl\\qdldl-config.cmake exit 1  # [win]

about:
  home: https://github.com/osqp/qdldl
  license: Apache-2.0
  license_file: LICENSE
  summary: A free LDL factorisation routine.

extra:
  recipe-maintainers:
    - traversaro
    - h-vetinari
