context:
  version: "0.1.9"

package:
  name: libqdldl
  version: ${{ version }}

source:
  - url: https://github.com/osqp/qdldl/archive/v${{ version }}.tar.gz
    sha256: 7d1285b2db15cf2730dc83b3d16ed28412f558591108cca4f28d4438bf72ceed

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - if: not win
      then: make
    - cmake
  run_exports:
    - ${{ pin_subpackage('libqdldl', upper_bound='x.x.x') }}

tests:
  - package_contents:
      lib:
        - qdldl
      include:
        - qdldl/qdldl.h
      files:
        - if: win
          then: |
            Library\lib\cmake\qdldl\qdldl-config.cmake
          else: |
            lib/cmake/qdldl/qdldl-config.cmake

about:
  homepage: https://github.com/osqp/qdldl
  license: Apache-2.0
  license_file: LICENSE
  summary: A free LDL factorisation routine.

extra:
  recipe-maintainers:
    - traversaro
    - h-vetinari
